/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PriceDisplay;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public String showNew(String item, double price, double fee) {
        Double newtotal = price + fee;
        String output = String.format("The price of the %s is: %f", item, newtotal);
        return output;
      }
}
